# Default .runtimerc.toml config file
# Format: https://github.com/toml-lang/toml

# Runtime.js directory path
RuntimePath = "${HOME}/runtime"

# Cross compiler root path
CrossCompilerPath = "${HOME}/opt/cross"
